### ISSUE TITLE
Plant spawned using give command does not grow over time.

### ISSUE THREAD

**Issue by smsunarto** [Terasology/PlantPack#11]
When I tried to plant corn1 that I got from typing 'give corn1' at the command console, the corn does not grow over time. It just stays in corn1 growth stage and does not move to the next stage (corn2).

**Comment by jdrueckert** [comment]
This is due to `PlantPack` being an asset-only module. It does not come with any logic that actually implements the growing.
To see growth, the `ChangingBlocks` module needs to be enabled.
Currently, there's an [open bug](https://github.com/Terasology/ChangingBlocks/issues/14) and a [fix](https://github.com/Terasology/ChangingBlocks/pull/15) waiting for review, but with that and #20 this should work again :slightly_smiling_face:

#20 also references `ChangingBlocks` a bit more clearly in the README.
